title: "Dan Stone"
description: "Dan Stone's personal blog about programming stuff."
author: Daniel Stone
logo: /static/img/avatar.png
github: https://github.com/daniel-stoneuk
about: "15 year old Android Developer."

baseurl: ""
url: "http://daniel-stone.uk"

disqus_shortname: daniel-stoneuk

share:
  twitter_username: daniel_stoneuk


enableTags: true
tagarray: ["Android", "Java", "GCSE Computer Science"]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]


prose:
  siteurl: "http://daniel-stone.uk"
  media: "assets"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "categories"
        field:
          label: "Categories"
          element: "multiselect"
          placeholder: "Select categories"
          options:
            - name: "Android"
              value: "android"
            - name: "Blog Post"
              value: "blog-post"
